#include <openssl/rand.h>
#define crypto_encrypt_ronald3072_openssl_MODULUSBITS 3072 
#define crypto_encrypt_ronald3072_openssl_MODULUSBYTES (crypto_encrypt_ronald3072_openssl_MODULUSBITS / 8)

#define crypto_encrypt_ronald3072_openssl_SECRETKEYBYTES (crypto_encrypt_ronald3072_openssl_MODULUSBYTES * 8)
#define crypto_encrypt_ronald3072_openssl_PUBLICKEYBYTES (crypto_encrypt_ronald3072_openssl_MODULUSBYTES)
#define crypto_encrypt_ronald3072_openssl_BYTES (crypto_encrypt_ronald3072_openssl_MODULUSBYTES)
