#define crypto_dh crypto_dh_curve2251_relic_amd64_clmul
#define crypto_dh_keypair crypto_dh_curve2251_relic_amd64_clmul_keypair
#define crypto_dh_SECRETKEYBYTES crypto_dh_curve_2251_relic_amd64_clmul_SECRETKEYBYTES
#define crypto_dh_PUBLICKEYBYTES crypto_dh_curve_2251_relic_amd64_clmul_PUBLICKEYBYTES
#define crypto_dh_BYTES crypto_dh_curve_2251_relic_amd64_clmul_BYTES
