#define CRYPTO_PRIVATEKEYBYTES     280
#define CRYPTO_PUBLICKEYBYTES     1574

#define CRYPTO_SECRETKEYBYTES \
  ( CRYPTO_PRIVATEKEYBYTES \
    + CRYPTO_PUBLICKEYBYTES)
#define CRYPTO_BYTES    CRYPTO_PUBLICKEYBYTES
