#define NumberRows 7
#define NumberColumns 8
#define SizeElement 5
#define RateSizeElements 8 
#define RateSizeBytes 5 
#define KeySizeElements 24
#define KeySizeBytes 15
#define NonceSizeElements 24
#define NonceSizeBytes 15
#define TagSizeElements 24
#define TagSizeBytes 15
#define CapacitySize 48
#define StateSize 56
#define p1rounds 12
#define p4rounds 12