#include "crypto_sign.h"

#define PRIME_BYTES crypto_sign_donald2048_openssl_PRIMEBYTES
#define SECRETKEY_BYTES crypto_sign_donald2048_openssl_SECRETKEYBYTES
#define PUBLICKEY_BYTES crypto_sign_donald2048_openssl_PUBLICKEYBYTES
#define SHORTHASH_BYTES 64
#define SIGNATURE_BYTES 40
