#include <openssl/rand.h>
#define crypto_sign_ronald1536_openssl_MODULUSBITS 1536 
#define crypto_sign_ronald1536_openssl_MODULUSBYTES (crypto_sign_ronald1536_openssl_MODULUSBITS / 8)

#define crypto_sign_ronald1536_openssl_SECRETKEYBYTES (crypto_sign_ronald1536_openssl_MODULUSBYTES * 8)
#define crypto_sign_ronald1536_openssl_PUBLICKEYBYTES (crypto_sign_ronald1536_openssl_MODULUSBYTES)
#define crypto_sign_ronald1536_openssl_BYTES (crypto_sign_ronald1536_openssl_MODULUSBYTES)
