#include <openssl/rand.h>
#define CRYPTO_MODULUSBITS 4096 
#define CRYPTO_MODULUSBYTES ( CRYPTO_MODULUSBITS / 8)

#define CRYPTO_SECRETKEYBYTES ( CRYPTO_MODULUSBYTES * 8)
#define CRYPTO_PUBLICKEYBYTES ( CRYPTO_MODULUSBYTES)
#define CRYPTO_BYTES ( CRYPTO_MODULUSBYTES)
