#define crypto_dh_kumjacfp127g_v01_var_SECRETKEYBYTES 32
#define crypto_dh_kumjacfp127g_v01_var_PUBLICKEYBYTES 48
#define crypto_dh_kumjacfp127g_v01_var_BYTES 48

#define SECRETKEY_BYTES crypto_dh_kumjacfp127g_v01_var_SECRETKEYBYTES
#define PUBLICKEY_BYTES crypto_dh_kumjacfp127g_v01_var_PUBLICKEYBYTES
#define SHAREDSECRET_BYTES crypto_dh_kumjacfp127g_v01_var_BYTES
