#include <openssl/rand.h>
#define crypto_sign_ecdonaldb409_openssl_PRIMEBYTES 52
#define crypto_sign_ecdonaldb409_openssl_SECRETKEYBYTES (crypto_sign_ecdonaldb409_openssl_PRIMEBYTES * 3)
#define crypto_sign_ecdonaldb409_openssl_PUBLICKEYBYTES (crypto_sign_ecdonaldb409_openssl_PRIMEBYTES * 2)
#define crypto_sign_ecdonaldb409_openssl_BYTES (crypto_sign_ecdonaldb409_openssl_PRIMEBYTES * 2)
