#include <openssl/rand.h>
#define crypto_sign_donald512_openssl_PRIMEBITS 512
#define crypto_sign_donald512_openssl_PRIMEBYTES (crypto_sign_donald512_openssl_PRIMEBITS / 8)

#define crypto_sign_donald512_openssl_SECRETKEYBYTES (crypto_sign_donald512_openssl_PRIMEBYTES + 20)
#define crypto_sign_donald512_openssl_PUBLICKEYBYTES crypto_sign_donald512_openssl_PRIMEBYTES
#define crypto_sign_donald512_openssl_BYTES 40
