#include <openssl/rand.h>
#define crypto_sign_ecdonaldb571_openssl_PRIMEBYTES 72
#define crypto_sign_ecdonaldb571_openssl_SECRETKEYBYTES (crypto_sign_ecdonaldb571_openssl_PRIMEBYTES * 3)
#define crypto_sign_ecdonaldb571_openssl_PUBLICKEYBYTES (crypto_sign_ecdonaldb571_openssl_PRIMEBYTES * 2)
#define crypto_sign_ecdonaldb571_openssl_BYTES (crypto_sign_ecdonaldb571_openssl_PRIMEBYTES * 2)
