#define NumberRows 5
#define NumberColumns 8
#define SizeElement 5
#define RateSizeElements 8 
#define RateSizeBytes 5 
#define KeySizeElements 32
#define KeySizeBytes 20
#define NonceSizeElements 16
#define NonceSizeBytes 10
#define TagSizeElements 32
#define TagSizeBytes 20
#define CapacitySize 32
#define StateSize 40
#define p1rounds 12