#define NumberRows 7
#define NumberColumns 8
#define SizeElement 5
#define RateSizeElements 8 
#define RateSizeBytes 5 
#define KeySizeElements 48
#define KeySizeBytes 30
#define NonceSizeElements 24
#define NonceSizeBytes 15
#define TagSizeElements 48
#define TagSizeBytes 30
#define CapacitySize 48
#define StateSize 56
#define p1rounds 12