#include <openssl/rand.h>
#define crypto_sign_ecdonaldp256_openssl_PRIMEBYTES 32
#define crypto_sign_ecdonaldp256_openssl_SECRETKEYBYTES (crypto_sign_ecdonaldp256_openssl_PRIMEBYTES * 3)
#define crypto_sign_ecdonaldp256_openssl_PUBLICKEYBYTES (crypto_sign_ecdonaldp256_openssl_PRIMEBYTES * 2)
#define crypto_sign_ecdonaldp256_openssl_BYTES (crypto_sign_ecdonaldp256_openssl_PRIMEBYTES * 2)
