#define NumberRows 5
#define NumberColumns 8
#define SizeElement 5
#define RateSizeElements 8 
#define RateSizeBytes 5 
#define KeySizeElements 16
#define KeySizeBytes 10
#define NonceSizeElements 16
#define NonceSizeBytes 10
#define TagSizeElements 16
#define TagSizeBytes 10
#define CapacitySize 32
#define StateSize 40
#define p1rounds 12
#define p2rounds 6
#define p3rounds 6